build.gradle modified

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -43,18 +43,13 @@ jobs:
 
       - name: Decode keystore
         run: |
+          echo "Decoding KEYSTORE_BASE64..."
           mkdir -p android/app
-          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/release-key.p12
-          chmod 644 android/app/release-key.p12
-      - name: Create key.properties
-        run: |
-          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > android/key.properties
-          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
-          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
-          echo "storeFile=/home/runner/work/drip/drip/android/app/release-key.p12" >> android/key.properties
-          cat android/key.properties
-          if [ ! -s android/key.properties ]; then echo "key.properties file is empty or not created"; exit 1; fi
-          echo "key.properties file created successfully."
+          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/release-key.jks || { echo "Failed to decode KEYSTORE_BASE64"; exit 1; }
+          chmod 644 android/app/release-key.jks
+          ls -l android/app/
+          if [ ! -s android/app/release-key.jks ]; then echo "Keystore file is empty or not created"; exit 1; fi
+          echo "Keystore file created successfully."
 
       - name: Verify keystore file
         run: |
@@ -75,6 +70,16 @@ jobs:
           ls -l android/app/
           echo "Full path to keystore: $(realpath android/app/release-key.jks)"
           if [ -f android/app/release-key.jks ]; then echo "Keystore file exists"; else echo "Keystore file missing"; exit 1; fi
+
+      - name: Create key.properties
+        run: |
+          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > android/key.properties
+          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
+          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
+          echo "storeFile=/home/runner/work/drip/drip/android/app/release-key.jks" >> android/key.properties
+          cat android/key.properties
+          if [ ! -s android/key.properties ]; then echo "key.properties file is empty or not created"; exit 1; fi
+          echo "key.properties file created successfully."
 
       - name: Install dependencies
         run: flutter pub get
@@ -97,7 +102,7 @@ jobs:
       - name: Build AAB (oroProduction flavor)
         env:
           CI: true
-        run: flutter build appbundle --release --flavor oroProduction -t lib/main_oroProduction.dart
+        run: flutter build appbundle --release --flavor oroProduction -t lib/main_oroProduction.dart --build-name=1.0.0 --build-number=2 --no-tree-shake-icons
 
       - name: Verify AAB file
         run: |
